import type { Metadata } from 'next';
import Link from 'next/link';
import { PageHeader } from '@/components/PageHeader';
import { LEGAL } from '@/lib/legal';

export const metadata: Metadata = {
  title: 'Terms of Service — Competitive Vibing',
  description: 'The agreement between you and Competitive Vibing when you use the service.',
};

export default function TermsPage() {
  return (
    <article className="mx-auto max-w-2xl pb-16">
      <PageHeader
        title="Terms of Service"
        description={`Last updated ${LEGAL.updated}. Plain language, on purpose.`}
      />

      <div className="prose mt-8 max-w-none text-[17px] leading-relaxed text-foreground dark:prose-invert prose-headings:font-semibold prose-headings:tracking-title prose-h2:mt-10 prose-h2:text-[22px] prose-p:my-4 prose-li:my-1.5 prose-a:text-primary prose-a:no-underline hover:prose-a:underline prose-strong:font-semibold">
        <p>
          By signing in to {LEGAL.appName} you agree to these terms. If you don’t agree, don’t
          use the service.
        </p>

        <h2>What the service is</h2>
        <p>
          {LEGAL.appName} is a practice tool for technical interviews. You read a programming
          problem, explain how you would solve it in plain language, and an AI grades the
          explanation and asks follow-up questions. It does not run code, and it is not a
          substitute for an interviewer, a tutor, or your own judgement.
        </p>

        <h2>Your account</h2>
        <ul>
          <li>You sign in with a Google account you are entitled to use.</li>
          <li>You must be at least 13 years old.</li>
          <li>You are responsible for what happens under your account.</li>
          <li>
            You can delete your account at any time from your Profile. Deletion is immediate
            and permanent.
          </li>
        </ul>

        <h2>Acceptable use</h2>
        <p>Please don’t:</p>
        <ul>
          <li>
            Try to break, overload or probe the service — including attempts to bypass the
            per-account evaluation limit or to manipulate the AI into behaving outside its
            purpose.
          </li>
          <li>Use automated tools to submit explanations or scrape content.</li>
          <li>Submit content that is unlawful, abusive, or that you don’t have the right to share.</li>
          <li>Copy the problem bank or the AI’s output for commercial redistribution.</li>
        </ul>
        <p>We may suspend or close accounts that do these things, without notice if necessary.</p>

        <h2>The AI can be wrong</h2>
        <p>
          Grades, commentary, follow-up questions and counterexamples are generated by a
          language model against a fixed rubric. They are designed to be useful and are checked
          where we can check them — counterexamples in particular are independently verified
          before they are shown — but they can still be mistaken, incomplete, or inconsistent.
          Treat them as a knowledgeable peer’s opinion, not an authority. Don’t make important
          decisions on the strength of a score.
        </p>

        <h2>Fair use limits</h2>
        <p>
          Each account may request up to ten AI evaluations per hour. This keeps the service
          affordable and available for everyone. The limit may change; the current value is
          shown in the app when you reach it.
        </p>

        <h2>Content and ownership</h2>
        <ul>
          <li>
            <strong>Your explanations are yours.</strong> You keep all rights to what you write.
            You give us permission to store it, send it to our AI provider for grading, and show
            it back to you — nothing more.
          </li>
          <li>
            <strong>Problem statements, hints and AI output are ours.</strong> The problems are
            original writing based on well-known interview problem categories. You may use them
            for your own practice; you may not republish them as a collection.
          </li>
          <li>
            If you opt in to the leaderboard you permit us to show your name, photo, XP, level
            and solved count to other users until you opt out.
          </li>
        </ul>

        <h2>Availability</h2>
        <p>
          The service is provided as is. We aim to keep it up but make no promise of
          uninterrupted availability, and we may change or discontinue features. If we ever
          shut the service down, we will give reasonable notice and a way to export your data.
        </p>

        <h2>Liability</h2>
        <p>
          To the fullest extent the law allows, {LEGAL.appName} is not liable for any loss
          arising from your use of the service, including reliance on AI output or an interview
          outcome. Nothing in these terms excludes rights you have under the Australian
          Consumer Law that cannot be excluded.
        </p>

        <h2>Privacy</h2>
        <p>
          How we handle your data is described in the{' '}
          <Link href="/privacy">Privacy Policy</Link>, which forms part of these terms.
        </p>

        <h2>Changes to these terms</h2>
        <p>
          We may update these terms. The date at the top will change, and for significant
          changes we will tell you in the app before they take effect. Continuing to use the
          service after that means you accept the new terms.
        </p>

        <h2>Governing law</h2>
        <p>These terms are governed by the laws of {LEGAL.operatorLocation}.</p>

        <h2>Contact</h2>
        <p>
          <a href={`mailto:${LEGAL.contactEmail}`}>{LEGAL.contactEmail}</a>
        </p>
      </div>
    </article>
  );
}
